### PR TITLE
Allow instrumentation to be suppressed when making outbound requests

### PR DESCRIPTION
**Pull request by nblumhardt**
A potential solution to #41 that doesn't add any additional hard dependencies.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for checking it out, @loomis 👍 

The wrapper sink approach would struggle because the requests to suppress happen asynchronously, on `PeriodicBatchingSink`'s background thread. There could definitely be more elegant ways to solve the problem, though.

Perhaps we are best waiting to see what other kinds of integration points/extension points become interesting post-1.0, and then consider this as potentially being part of a broader interface? I'm happy leaving this open in draft or closing it for now, whichever makes life easiest 😄

**Comment by loomis** [comment]
@nblumhardt Would agree with waiting to implement this post-1.0. Don't have any issue with leaving the PR open.

**Comment by adameasten** [comment]
Any progress on this one? I'm currently migrating from a Serilog.Sink that writes directly to a Observability backend and instead targeting otelcollector. It would have been a much smoother transition if i could just switch to this sink (keep enrichers and so on),
but it's not possible until suppression of tracing for outbund requests.

**Comment by nblumhardt** [comment]
Hi @adameasten; I've just updated this branch with changes from `dev`; the NUPKG build is at:

https://ci.appveyor.com/project/serilog/serilog-sinks-opentelemetry/builds/47467903/artifacts

(You'll need to download it and add a local folder as a package source in order to reference it in your project.)

It'd be great to get some feedback on how this works for you - we're still in the "information gathering" phase and trying to figure out how best to enable this :-)

**Comment by adameasten** [comment]
@nblumhardt Great, thank you! 
I'll try it out and give you some feedback :)

**Comment by nblumhardt** [comment]
Awesome, thanks @adameasten 👍  - let me know if you need any help getting it configured.

**Comment by adameasten** [comment]
Do you have any thoughts around exporting Activities too. Not only enriching logs with Trace/Span id, but also send the [Trace objects](https://opentelemetry.io/docs/concepts/signals/traces/) with the sink to a OTEL collector? Should i implement my own OpenTelemtry.BaseExporter<T> and inject a Serliog.Logger that is configured to send the data to the right endpoint? ex:

```
var log = new LoggerConfiguration().WriteTo.OpenTelemetry();
var traceExporter = new TraceExporter(log);

public class TraceExporter : OpenTelemtry.BaseExporter<System.Diagnostics.Activity>
{
        private readonly Serilog.ILogger _logger;
        public TraceExporter(Serilog.ILogger logger)
        {
                _logger = logger;
        }

        public override ExportResult Export(in Batch<System.Diagnostics.Activity> batch)
        {
               //loop over batch of activities and create LogEventProperties
               _logger.LogEvent(........, properties);
        }
}

```
Don't know if it makes sense @nblumhardt, but i want to be able to see both logs and use a front end to build graphs based on Activities (Traces)

**Comment by adameasten** [comment]
@loomis Aha okay, i see! Read through the comments and it makes sense! 
I do think it is i a good idea to integrate handling of the different Signals (Traces, metrics, logs) in the future, so you can rely on the same framework for smooth implementation. I'll probably stick to OpenTelemtry SDK for now, but i'll keep en eye on the development. 

I'm working quite alot with distributed tracing in my current role, so i'm happy to help if needed! Thanks for the input.

**Comment by nblumhardt** [comment]
Closing until I have a chance to rethink :-)

**Pull request closed without merging**
