### PR TITLE
Add level switch support

### PR DESCRIPTION
**Pull request by nblumhardt**
Serilog sinks should typically support both `restrictedToMinimumLevel` and `levelSwitch`; added to the configuration extension.

(@SimonCropp here's another example of the same problem; code written very recently. I think we might be stuck rolling back https://github.com/serilog/serilog/pull/1800.)

### CODE REVIEW

**Comment by SimonCropp** [comment]
happy to roll back. but hopefully @nblumhardt can confirm

**Comment by nblumhardt** [comment]
@SimonCropp I guess when we start to run compat tests it'll all become clearer pretty quickly :-)

**Comment by loomis** [comment]
@nblumhardt Can you increment the version number and merge this (assuming there are no issues)?

**Comment by nblumhardt** [comment]
Re the version number, the default Serilog build scripts add a prerelease version tag, such as `-dev-00123`, which lets us keep the `<VersionPrefix>` field constant during development work. For this package we can set the version to `1.0.0`, and CI will produce `1.0.0-dev-NNNNN` prerelease builds until we merge to main. Saves a lot of mucking around with version increments - does that work for you @loomis ? I can update here either way 👍

**Comment by loomis** [comment]
@nblumhardt That's fine. Let's go with that. Thanks.

**Pull request merged**
