### PR TITLE
Reduce memory allocations in HttpExporter

### PR DESCRIPTION
**Pull request by shatl**
Use `ArrayPool` instead of new buffer allocation when sending logs to OpenTelemetry collector.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Looks great to me, but I'm not familiar with `CodedOutputStream`, which the original code uses but the replacement doesn't. Is this intended, or an oversight? Thanks!

**Comment by shatl** [comment]
This was done on purpose since CodedOutputStream does not support `Span`

**Comment by nblumhardt** [comment]
Thanks for the follow-up! Was the encoding performed by `CodedOutputStream` unnecessary in this case?

**Comment by loomis-relativity** [comment]
The encoding doesn't do anything in this case. PR LGTM. Merging...

**Comment by loomis** [comment]
Thanks for the contribution.

**Pull request merged**
